networks:
  default:
    external: false
volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
services:
  xtrade:
    build:
      context: .
      target: release-xtrade
    restart: unless-stopped
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://apm:8200
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=True
      - OTEL_EXPORTER_OTLP_METRICS_INSECURE=True
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_RESOURCE_ATTRIBUTES=service.name=xtrade,service.version=0.0.1,deployment.environment=production
    ports:
      - "127.0.0.1:8080:8080"
      - "[::1]:8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      apm:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 768m
  xcache:
    build:
      context: .
      target: release-xcache
    restart: unless-stopped
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://apm:8200
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=True
      - OTEL_EXPORTER_OTLP_METRICS_INSECURE=True
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_RESOURCE_ATTRIBUTES=service.name=xcache,service.version=0.0.1,deployment.environment=production
#      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
#      - OTEL_TRACES_SAMPLER_ARG=0.01
    ports:
      - "127.0.0.1:8180:8080"
      - "[::1]:8180:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      apm:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 2G
  rbcs-client:
    build:
      context: deploy/rbcs
    profiles:
      - benchmark
    depends_on:
      xcache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 512m
  apm:
    image: docker.elastic.co/apm/apm-server:${STACK_VERSION}
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    command: ["--strict.perms=false"]
    ports:
      - "127.0.0.1:8200:8200"
    volumes:
      - ./deploy/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512m
    depends_on:
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    build:
      context: deploy/elasticsearch
      args:
        STACK_VERSION: ${STACK_VERSION}
    restart: unless-stopped
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.apm_data.enabled=true
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q '\"name\" : \"elasticsearch\"'",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    restart: unless-stopped
    ports:
      - "127.0.0.1:5601:5601"
    volumes:
      - ./deploy/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - kibana-data:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    depends_on:
      elasticsearch:
        condition: service_healthy
  redis:
    image: redis:${REDIS_VERSION}-alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 1024m
  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 128m